# Generated by Django 3.2 on 2021-04-23 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offers', '0001_initial'),
        ('needs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='need',
            name='offer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.offer'),
        ),
    ]
